app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


use Illuminate\Support\Facades\Redirect;

Route::get('/', 'PublicController@index');

Route::get('home', 'PublicController@index');
Route::get('about', 'PublicController@showAbout');
Route::get('projects', 'PublicController@showProjects');
Route::get('contact-us', 'PublicController@showContact');
Route::get('videos', 'PublicController@showVideos');
Route::get('gallery', 'PublicController@showGallary');
// Route::post('contact-us', ['as'=>'sendmessage', 'uses'=>'PublicController@postEmail']);
Route::post('sendmessage', function(){
    $input = \Input::all();
        Mail::queue('__partials/data/sendmail', ['input'=>$input] , function($message) use($input){

            $email = "thebalancegambia@gmail.com";
            $message->to($email)
                    ->subject($input['subject']);

        });

    return redirect()->to('home');
});

Route::get('signup', 'PublicController@showSignup');
Route::post('signup', 'PublicController@postSignup');
Route::get('approved', 'MembersshipsController@showApproved');
Route::get('unapproved', 'MembersshipsController@showUnapproved');
Route::resource('memberships', 'MembersshipsController');

Route::resource('sessions','SessionsController');

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('admin', 'AdminController');
//    Route::get('auth/register', 'Auth\AuthController@getRegister');
});


Route::any('download/{url}/{filename}',function($url,$filename){


	if(File::exists($url)) return response()->download(public_path().'/'.$url.'/'.$filename);

	return redirect()->back();

});

resources/views/inc/admin_header.blade.php
<!DOCTYPE HTML>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width-device-width initial-scale=1" >

		<meta name="description" content="The Balance Official Website">
		<meta name="authors" content="Musa Touray <mkadsamba86@gmail.com>, mamadou jallow <sulsiralumo@gmail.com">
		<title>The Balance - @yield('title', 'this is our defualt')</title>

				<!-- bootstrap -->
				{!! Html::style('css/bootstrap.min.css') !!}
                {!! Html::style('css/bootstrap-theme.min.css') !!}
                {!! Html::style('css/carousel.css') !!}
                {!! Html::style('css/style.css') !!}
        	    {!! Html::style('css/admin.css') !!}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
{!! Html::style('css/lightbox.css') !!}


		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	    <!--[if lt IE 9]>
	      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	    <![endif]-->
	</head>
	<body>

resources/views/inc/admin_nav.blade.php
						<header id="nav-header" class="clearfix">
							<div class="col-md-5">
								<ul class="pull-right">

									<li id="welcome" class="hidden-xs"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Welcome {!! ucwords(Auth::user()->name) !!}</li>
									<li>
										<a href="{{url('/')}}" class="logout">
											<span class="glyphicon glyphicon-home" aria-hidden="true"></span>
											Home <!-- logout icon -->
										</a>
									</li>
									<li>
										<a href="{{url('signup')}}" class="logout">
											<span class="glyphicon glyphicon-registration-mark" aria-hidden="true"></span>
											Create Member <!-- logout icon -->
										</a>
									</li>
									<li>
										<a href="{{route('admin.create')}}" class="logout">
											<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
											Create Users <!-- logout icon -->
										</a>
									</li>
								</ul>
							</div>

							<div class="col-md-7">
								<ul class="pull-right">
																	<li>
                                										<a href="{{url('home')}}" class="logout">
                                											<span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
                                											Public Site <!-- logout icon -->
                                										</a>
                                									</li>

									<li class="fixed-width">
										<a href="#">
											<span class="glyphicon glyphicon-bell" aria-hidden="true"></span>
											<span class="label label-warning">0</span> <!-- alert to autenticate new members -->
										</a>
									</li>
									<li class="fixed-width">
										<a href="#">
											<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
											<span class="label label-message">0</span> <!-- alert to check recieved messages -->
										</a>
									</li>
									<li>
										<a href="{{url('auth/logout')}}" class="logout">
											<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
											Log out <!-- logout icon -->
										</a>
									</li>
								</ul>
							</div>
						</header>

resources/views/inc/featured.blade.php
		<!-- CAROUSEL
		======================================================= -->
		<div id="myCarousel" class="carousel slide" data-ride="carousel">

			<ol class="carousel-indicators">
				<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
				<li data-target="#myCarousel" data-slide-to="1"></li>
				<li data-target="#myCarousel" data-slide-to="2"></li>
			</ol>
			<div class="carousel-inner" role="listbox">
				<div class="item active">
					<img class="first-slide" src="img/foto4.jpg" alt="first slide">
					<div class="container">
						<div class="carousel-caption">
							<h1>Welcome to The Balance</h1>
							<p class="carousel-msg">Learn, think and create an innovative project
								in an interesting and entertaining platform with a mentor</p>
							<p><a class="btn btn-lg btn-primary" href="about" role="button">Learn more &raquo;</a></p>
						</div>
					</div>
				</div>

				<div class="item">
					<img class="second-slide" src="img/boat.jpg" alt="second slide">
					<div class="container">
						<div class="carousel-caption">
							<h1>Start a Project</h1>
							<p class="carousel-msg">Want to brainstorm or are you ready to start a project? We are here to listen. Our team of experts will guide you through into any venture</p>
							<p><a class="btn btn-lg btn-primary" href="signup" role="button">Sign up today &raquo;</a></p>
						</div>
					</div>
				</div>
				
				<div class="item">
					<img class="third-slide" src="img/sample2.jpg" alt="third slide">
					<div class="container">
						<div class="carousel-caption">
							<h1>View Our Shows</h1>
							<p class="carousel-msg">View our gallery of pictures and video clips to see the magic that happens at The Balance TV and Talk Shows</p>
							<p><a class="btn btn-lg btn-primary" href="gallery" role="button">Browse Gallery &raquo;</a></p>
						</div>
					</div>
				</div>
			</div>

			<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
				<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			</a>
			<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
				<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			</a>
		</div>

resources/views/inc/footer.blade.php
          	<!-- FOOTER
    		======================================================= -->
    		<footer>
    			<div class="container">
    			     @if(!Auth::check())
    				<div class="navbar-text pull-left">
    					<a href="https://www.youtube.com/channel/UCUF_daaXZ-miCLCc1IFX6MA/playlists" target="_blank"><i class="fa fa-youtube-square fa-2x"></i></a>
    					<a href="https://facebook.com" target="_blank"><i class="fa fa-facebook-square fa-2x"></i></a>
    					<a href="https://twitter.com" target="_blank"><i class="fa fa-twitter-square fa-2x"></i></a>
    					<a href="https://instagram.com" target="_blank"><i class="fa fa-instagram fa-2x"></i></a>
    		        </div>
    		        @endif
			<div class="container">
				<div class="navbar-text pull-left">
		        	<p><b>Copyright </b>&copy; <?=date('Y')?> &middot; The Balance Crew | All Rights Reserved &middot;</p>
	        	</div>

            @if(Auth::check())
				<div class="navbar-text pull-center">
					Admin System
		        </div>
            @endif
		        <div>
	        		<p class="pull-right"><a href="#">Back to top</a></p>
	        	</div>
	       </div>

    	       </div>
    		</footer>


    		<!-- BOOTSTRAP CORE JAVASCRIPT
        ================================================== -->
        <div class="modal fade" id="videoModal" tabindex="1" role="dialog" aria-labelledby="videoModal" aria-hidden="true">
        	<div class="modal-dialog">
        		<div class="modal-content">
        			<div class="modal-body">
        				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        				<div>
        					<iframe width="100%" height="400" frameborder="0" allowfullscreen="" src=""></iframe>
        				</div>
        			</div>
        		</div>
        	</div>
        </div>

@include('__partials/modals/loginModal')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="assets/js/ie10-viewport-bug-workaround.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/lightbox.min.js"></script>
<script src="js/admin.js"></script>
    <script>
    $('.link').find("ul.collapseable").show();
    //FUNCTION TO GET AND AUTO PLAY YOUTUBE VIDEO FROM DATATAG
        autoPlayYouTubeModal();
      	function autoPlayYouTubeModal() {
          var trigger = $("body").find('[data-toggle="modal"]');
          trigger.click(function () {
              var theModal = $(this).data("target"),
                  videoSRC = $(this).attr("data-theVideo"),
                  videoSRCauto = videoSRC + "?autoplay=1";
              $(theModal + ' iframe').attr('src', videoSRCauto);
              $(theModal + ' button.close').click(function () {
                  $(theModal + ' iframe').attr('src', videoSRC);
              });
          });
      }
    </script>




	</body>
</html>

resources/views/inc/header.blade.php
<!DOCTYPE HTML>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width-device-width initial-scale=1" >

		<meta name="description" content="The Balance Official Website, The Balance - learn, think and create">
		<meta name="authors" content="Musa Touray <mkadsamba86@gmail.com>, mamadou jallow <sulsiralumo@gmail.com">
		<title>The Balance - learn, think and create @yield('title')</title>

				<!-- bootstrap -->
				{!! Html::style('css/bootstrap.min.css') !!}
                {{-- {!! Html::style('css/bootstrap-theme.min.css') !!} --}}
                {!! Html::style('css/carousel.css') !!}
        	    {!! Html::style('css/style.css') !!}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
{!! Html::style('css/lightbox.css') !!}


		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	    <!--[if lt IE 9]>
	      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	    <![endif]-->
	</head>
	<body>


			<!-- NAVBAR
    		======================================================= -->
    		<div class="navbar-wrapper">
    			<div class="container">
    				<nav class="navbar navbar-inverse navbar-static-top">
    					<div class="container">
    						<div class="navbar-header">
    							<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="true" aria-controls="navbar">
    								<span class="sr-only">Toggle Navigation</span>
    								<span class="icon-bar"></span>
    								<span class="icon-bar"></span>
    								<span class="icon-bar"></span>
    							</button>
    							<a class="navbar-brand {{set_active('/')}}" href="/">The Balance</a>
    						</div>
    						<div id="navbar" class="navbar-collapse collapse">
    							<ul class="nav navbar-nav">
    								<li class="{{set_active('home')}}"><a href="{{url('home')}}">Home</a></li>
    								<li class="{{set_active('about')}}"><a href="{{url('about')}}">About</a></li>
    								<li class="dropdown"  class="{{set_active('projects')}}">
    									<a href="{{url('projects')}}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Projects<span class="caret"></span></a>
    									<ul class="dropdown-menu">
    									    @if(Auth::check())
    									    <li><a href="{{route('admin.index')}}" >Admin Dashboard</a></li>

    									    @else
    									    <li><a href="#admin-dashboard" data-toggle="modal">Admin Dashboard</a></li>
    									    @endif

    										<li role="separator" class="divider"></li>
    										<li><a href="#">Start a Project</a></li>
    										<li><a href="#">Finished Projects</a></li>
    										<li><a href="#">Our Partners</a></li>
    										<li role="separator" class="divider"></li>
    										<li><a href="#">Terms &amp; Conditions</a></li>
    									</ul>
    								</li>
								<li class="{{set_active('contact-us')}}"><a href="{{url('contact-us')}}">Contact Us</a></li>
								<li><a href="#videos" data-toggle="modal" data-target="#videoModal" data-theVideo="http://youtube.com/embed/0zrIMJfZAAw?list=PLj89c1y-Pmlp4EikIX4wfioV3p7Vf70LT">
								<button type="button" class="vid-transparent">Watch Videos</button></a></li>
    							</ul>

    								<ul class="nav navbar-nav navbar-right">

                                		    							    @if(Auth::check())
                                                                                <li><a href="{{url('auth/logout')}}"><button type="button" class="btn btn-success">Log out</button></a></li>
                                            							    @else
                                            							    <li><a href="#admin-dashboard" data-toggle="modal"><button type="button" class="btn btn-success">Admin Login</button></a></li>
                                            							    @endif
                                        <li><a href="signup"><button type="button" class="btn btn-primary">Sign Up</button></a></li>
                                	</ul>
    						</div>
    					</div>
    				</nav>

    			</div>
    		</div>

resources/views/inc/sidebar.blade.php
				@inject('count','App\Member')

				<div class="col-md-2 col-sm-1 hidden-xs display-table-cell valign-top" id="sidebar">
					<h1 class="hidden-xs hidden-sm">The Balance</h1>
					<ul>
						<li class="link active">
							<a href="{{route('admin.index')}}">
								<span class="fa fa-home fa-3x" aria-hidden="true"></span>
								<span class="hidden-sm hidden-xs">Dashboard</span>
							</a>
						</li>
						<li class="link ">
							<a href="#collapse-members" data-toggle="collapse" aria-controls="control-members">
								<span class="fa fa-users fa-3x" aria-hidden="true"></span>
								<span class="hidden-sm hidden-xs">Members</span>
							</a>
							<ul class="collapse collapseable" id="collapse-members">
								<li>
									<a href="{{url('approved')}}">Approved
										<span class="label label-success pull-right hidden-sm hidden-xs">{{$count->approved()->get()->count()}}</span>
									</a>
								</li>
								<li>
									<a href="{{url('unapproved')}}">Unapproved
										<span class="label label-warning pull-right hidden-sm hidden-xs">{{$count->unapproved()->get()->count()}}</span>
									</a>
								</li>
							</ul>
						</li>
					</ul>
				</div>
{{--{{dd($data->total())}}--}}