app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


use Illuminate\Support\Facades\Redirect;

Route::get('/', 'PublicController@index');

Route::get('home', 'PublicController@index');
Route::get('about', 'PublicController@showAbout');
Route::get('projects', 'PublicController@showProjects');
Route::get('contact-us', 'PublicController@showContact');
Route::get('videos', 'PublicController@showVideos');
Route::get('gallery', 'PublicController@showGallary');
// Route::post('contact-us', ['as'=>'sendmessage', 'uses'=>'PublicController@postEmail']);
Route::post('sendmessage', function(){
    $input = \Input::all();
        Mail::queue('__partials/data/sendmail', ['input'=>$input] , function($message) use($input){

            $email = "thebalancegambia@gmail.com";
            $message->to($email)
                    ->subject($input['subject']);

        });

    return redirect()->to('home');
});

Route::get('signup', 'PublicController@showSignup');
Route::post('signup', 'PublicController@postSignup');
Route::get('approved', 'MembersshipsController@showApproved');
Route::get('unapproved', 'MembersshipsController@showUnapproved');
Route::resource('memberships', 'MembersshipsController');

Route::resource('sessions','SessionsController');

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('admin', 'AdminController');
//    Route::get('auth/register', 'Auth\AuthController@getRegister');
});


Route::any('download/{url}/{filename}',function($url,$filename){


	if(File::exists($url)) return response()->download(public_path().'/'.$url.'/'.$filename);

	return redirect()->back();

});

resources/views/__partials/data/allmemebers.blade.php
							<table class="table table-hover all-members">
								<thead>
									<tr>
										<th>#</th>
										<th>Full Name</th>
										<th>Gender</th>
										<th>Nationality</th>
										<th>Occupation</th>
										<th>Address</th>
										<th>Phone</th>
										<th>Email</th>
										<th>Date</th>
										<th>Status</th>
									</tr>
								</thead>
								<tbody>
								    @if(!isset($data) and empty($data))
								    <tr>
								        <td colspan="10"><strong>Sorry there are no members yet!</strong></td>
								    </tr>
								    @else
								        @foreach($data as $key => $value)
								        <tr>
								                <td>{{$key + 1}}</td>
								                <td><a href="{{route('memberships.show',$value['id'])}}">{{ucwords($value['person']['fullname'])}}</a></td>
								                 <td>{{ucwords($value['person']['gender'])}}</td>
								                <td>{{ucwords($value['person']['nationalities'])}}</td>
								                <td>{{ucwords($value['person']['occupation'])}}</td>
								                <td>
								                    @if(isset($value['person']['contacts']))
                                                        {{ucwords($value['person']['contacts']['address'])}}
								                    @else
								                     -
								                    @endif
								                </td>
								                <td>
   								                    @if(isset($value['person']['contacts']))
                                                           {{ucwords($value['person']['contacts']['phone'])}}
   								                    @else
   								                     -
   								                    @endif
   								                </td>
								                <td>
   								                    @if(isset($value['person']['contacts']))
                                                           {{ucwords($value['person']['contacts']['email'])}}
   								                    @else
   								                     -
   								                    @endif
   								                </td>
   								                 <td>{{$value['person']['created_at']}}</td>
   								                 <td>
                                                      @if($value['status'] == 1)
                                                        <a href="{{route('memberships.show',[$value['id'],'setstatus'=>0])}}" class="label label-success">Approved</a>
                                                      @else
                                                       <a href="{{route('memberships.show',[$value['id'],'setstatus'=>1])}}" class="label label-warning">unapprove</a>
                                                      @endif
                                                  </td>
								        </tr>
                                        @endforeach
								    @endif

								</tbody>
							</table>

resources/views/__partials/data/approvedmembers.blade.php
							<table class="table table-hover all-members">
								<thead>
									<tr>
										<th>#</th>
										<th>Full Name</th>
										<th>Gender</th>
										<th>Nationality</th>
										<th>Occupation</th>
										<th>Address</th>
										<th>Phone</th>
										<th>Email</th>
										<th>Date</th>
										<th>Status</th>
									</tr>
								</thead>
								<tbody>
								    @if(!isset($data) and empty($data))
								    <tr>
								        <td colspan="10"><strong>Sorry there are no members yet!</strong></td>
								    </tr>
								    @else
								        @foreach($data as $key => $value)
								        <tr>
								        	<?php  $unique = $value['id'].'-'.str_random(28)  ?>
								                <td>{{$key + 1}}</td>
								                <td><a href="#{!! $unique !!}" data-toggle="modal" class="edit-record" data-id="1">{{ucwords($value['person']['fullname'])}}</a></td>
								                 <td>{{ucwords($value['person']['gender'])}}</td>
								                <td>{{ucwords($value['person']['nationalities'])}}</td>
								                <td>{{ucwords($value['person']['occupation'])}}</td>
								                <td>
								                    @if(isset($value['person']['contacts']))
                                                        {{ucwords($value['person']['contacts']['address'])}}
								                    @else
								                     -
								                    @endif
								                </td>
								                <td>
   								                    @if(isset($value['person']['contacts']))
                                                           {{ucwords($value['person']['contacts']['phone'])}}
   								                    @else
   								                     -
   								                    @endif
   								                </td>
								                <td>
   								                    @if(isset($value['person']['contacts']))
                                                           {{ucwords($value['person']['contacts']['email'])}}
   								                    @else
   								                     -
   								                    @endif
   								                </td>
   								                 <td>{{$value['person']['created_at']}}</td>
   								                 <td>
                                                      @if($value['status'] == 1)
                                                        <a href="{{route('memberships.show',[$value['id'],'setstatus'=>0])}}" class="label label-success">Approved</a>
                                                      @else
                                                       <a href="{{route('memberships.show',[$value['id'],'setstatus'=>1])}}" class="label label-warning">unapprove</a>
                                                      @endif
                                                  </td>

                                                  <td colspan="12">
                                                  	

												    <!-- MODAL MEMBERS RECORDS
											    ================================================== -->
													<div class="modal fade" id="{!!$unique!!}" tabindex="-1" role="dialog" aria-labelledby="membersModal">
											  			<div class="modal-dialog modal-lg">
											    			<div class="modal-content">
											      				<div class="modal-header">
											        				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
											        					<h4 class="modal-title" id="membersModal">Members Name</h4>
											      				</div>
											      				<div class="modal-body">
											      					<table class="table table-hover all-members">
																			<thead>
																				<tr>
																					
																					<th>Full Name</th>
																					<th>Gender</th>
																					<th>Nationality</th>
																					<th>Occupation</th>
																					<th>Address</th>
																					<th>Phone</th>
																					<th>Email</th>
																					<th>Date</th>
			
																				</tr>
																			</thead>
																			<tbody>
																				<tr>
																					
																					<td>{{ucwords($value['person']['fullname'])}}</td>
																					<td>{{ucwords($value['person']['gender'])}}</td>
																					<td>{{ucwords($value['person']['nationalities'])}}</td>
																					<td>{{ucwords($value['person']['occupation'])}}</td>
																			<td>
															                    @if(isset($value['person']['contacts']))
																                    {{ucwords($value['person']['contacts']['address'])}}
																                @else
																                 -
																                @endif															                    
														                    </td>
																			<td>
																			@if(isset($value['person']['contacts']))
				                                                            {{ucwords($value['person']['contacts']['phone'])}}
						   								                    @else
						   								                     -
						   								                    @endif
																			</td>
																			<td>
						   								                    @if(isset($value['person']['contacts']))
						                                                           {{ucwords($value['person']['contacts']['email'])}}
						   								                    @else
						   								                     -
						   								                    @endif																

																			</td>
																			<td>
																				{{$value['person']['created_at']}}

																			</td>
																					
																				</tr>
																				
																			</tbody>
																		</table>
											      				</div>
											      				<div class="modal-footer">

	      				@if( !($value->person->files->isEmpty()) )


	      					<a href="{!!
	      					 asset('download/'.'media/'.$value->person->files->toArray()[0]['renameFile']) 
	      					 !!}" class="btn btn-success">Download</a>
	      				@endif



																	<a href="{!! route('memberships.edit',$value['id']) !!}" class="btn btn-info" >Edit</a>

																	<button class="blanker">
																	{!! Form::open(['route'=>['memberships.destroy',$value['id']],'method'=>'delete', 'class'=>'form-inline']) !!}
																		<button type="submit" class="btn btn-danger">Delete </button>
																	{!! Form::close() !!}																		
																	</button>



											        				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
											      				</div>
											    			</div>
											  			</div>
													</div>



                                                  </td>

								        </tr>
                                        @endforeach
								    @endif

								</tbody>
							</table>

                                                  	

resources/views/__partials/data/sendmail.blade.php
<div class="row">
    <h1>{!! ucwords($input['subject']) !!}</h1>
    <strong>Sender: {!! ucwords($input['email']) !!}</strong>
    <p>
        {!! $input['message'] !!}
    </p>
</div>

resources/views/__partials/data/showmember.blade.php
		<!-- MEMBERSHIP FORM
		======================================================= -->

			<div class="form-header">
				<h2>The Balance Membership Form</h2>
				<p>Please read all the information carefully before completing the form. In order to be able to submit the form, you must fill in all the required fields denoted with <span class="red-star">&#9733;</span> symbol.</p>
			</div>

           &nbsp;&nbsp;
			<div class="form-group">
		    	<label for="inputInfo" class="col-sm-3 control-label legend">PERSONAL INFORMATION</label>
		  	</div>

		  	<div class="form-group">
		  		<label for="title" class="col-sm-2 control-label">Title</label>
		  		<div class="radio col-sm-2">
			  		<label class="radio-inline">
			  		    {!! Form::radio("person[title]","mr") !!}Mr.
			  		</label>
						&nbsp;&nbsp;&nbsp;&nbsp;
			  		<label class="radio-inline">
			  		        {!! Form::radio("person[title]","mrs") !!}Mrs.
			  		</label>

			  		<label class="radio-inline">

			  		{!! Form::radio("person[title]","miss") !!} Miss

			  		</label>

			  		<label class="radio-inline">
			  		{!! Form::radio("person[title]","dr") !!}Dr.
			  		</label>
			  	</div>

			  	<label for="gender" class="col-sm-2 control-label">Gender <span class="red-star">&#9733;</span></label>
			  	<div class="radio col-sm-2">
			  		<label class="radio-inline">
			  		{!! Form::radio("person[gender]","Male") !!}Male
			  		</label>

			  		<label class="radio-inline">
			  		{!! Form::radio("person[gender]","Female") !!}Female
			  		</label>
			  	</div>

			  	<label for="dob" class="col-sm-2 control-label">Date of Birth <span class="red-star">&#9733;</span></label>
		    	<div class="col-sm-2">
		    	{!! Form::date("person[dob]",$data->person['dob'], ["class"=>"form-control",  "placeholder"=>"Birthday"]) !!}
		    	</div>
		  	</div>
              &nbsp;&nbsp;&nbsp;
			<div class="form-group">
		    	<label for="inputSurname" class="col-sm-2 control-label">Surname <span class="red-star">&#9733;</span></label>
		    	<div class="col-sm-10">
		    	{!! Form::text("person[fullname]",$data->person['fullname'], ["class"=>"form-control",  "placeholder"=>"Family Name", "required"=> true]) !!}
		    	</div>
		  	</div>
		  	   &nbsp;&nbsp;&nbsp;

		  	<div class="form-group">
		    	<label for="inputNationality" class="col-sm-2 control-label">Nationality <span class="red-star">&#9733;</span></label>
		    	<div class="col-sm-10">
		    	    {!! Form::text("person[nationalities]",$data->person['nationalities'], ["class"=>"form-control",  "placeholder"=>"Country of birth"]) !!}

		    	</div>
		  	</div>
		  	&nbsp;&nbsp;&nbsp;

		  	<div class="form-group">
		    	<label for="inputOccupation" class="col-sm-2 control-label">Occupation <span class="red-star">&#9733;</span></label>
		    	<div class="col-sm-10">
		    	{!! Form::text("person[occupation]",$data->person['occupation'], ["class"=>"form-control",  "placeholder"=>"Occupation"]) !!}
		    	</div>
		  	</div>
		  	&nbsp;&nbsp;&nbsp;

		  	<div class="form-group">
		    	<label for="inputInfo" class="col-sm-3 control-label legend">CONTACT INFORMATION</label>
		  	</div>
		  	&nbsp;&nbsp;&nbsp;

		  	<div class="form-group">
		    	<label for="inputAddress" class="col-sm-2 control-label">Address <span class="red-star">&#9733;</span></label>
		    	<div class="col-sm-10">
		    	{!! Form::text("person[contact][address]",$data->person['contacts']['address'], ["class"=>"form-control",  "placeholder"=>"House Address"]) !!}
		    	</div>
		  	</div>
		  	&nbsp;&nbsp;&nbsp;

		  	<div class="form-group">
		    	<label for="inputPhone" class="col-sm-2 control-label">Phone Number <span class="red-star">&#9733;</span></label>
		    	<div class="col-sm-10">
		    	{!! Form::text("person[contact][phones]",$data->person['contacts']['phone'], ["class"=>"form-control",  "placeholder"=>"Telephone Number", "required"=> true]) !!}
		    	</div>
		  	</div>
		  	&nbsp;&nbsp;&nbsp;

		  	<div class="form-group">
		    	<label for="inputEmail" class="col-sm-2 control-label">Email Address</label>
		    	<div class="col-sm-10">
		    		{!! Form::email("person[contact][email]",$data->person['contacts']['email'], ["class"=>"form-control",  "placeholder"=>"Email", "required"=> true]) !!}
		    	</div>
		  	</div>
		  	&nbsp;&nbsp;&nbsp;&nbsp;

		  	<div class="form-group">
		    	<label for="inputEdu" class="col-sm-3 control-label legend">EDUCATIONAL BACKGROUND</label>
		  	</div>
		  	&nbsp;&nbsp;&nbsp;


@if(!isset($data->person['education']) or empty($data->person['education']))

		  	<div class="form-group">
		    	<label for="inputUni" class="col-sm-2 control-label">University/College</label>
		    	<div class="col-sm-4">
		    	{!! Form::text("school[university][name]",null, ["class"=>"form-control",  "placeholder"=>"Name of Last University or College Attended"]) !!}
		    	</div>
		    	<label for="inputUniYear" class="col-sm-2 control-label">Year Completed</label>
		    	<div class="col-sm-4">
		    	{!! Form::text("school[university][year]",null, ["class"=>"form-control",  "placeholder"=>"Year Completed"]) !!}

		    	</div>
		  	</div>
		  	&nbsp;&nbsp;&nbsp;

		  	<div class="form-group">
		    	<label for="inputSenior" class="col-sm-2 control-label">High/Senior School <span class="red-star">&#9733;</span></label>
		    	<div class="col-sm-4">

		    	    {!! Form::text("hschool[name]",null, ["class"=>"form-control",  "placeholder"=>"Name of Senior or High School Attended"]) !!}

		    	</div>
		    	<label for="inputSeniorYear" class="col-sm-2 control-label">Year Completed <span class="red-star">&#9733;</span></label>
		    	<div class="col-sm-4">
		    	{!! Form::text("hschool[year]",null, ["class"=>"form-control",  "placeholder"=>"Year Completed"]) !!}

		    	</div>
		  	</div>
		  	&nbsp;&nbsp;&nbsp;

		  	<div class="form-group">
		    	<label for="inputJunior" class="col-sm-2 control-label">Upper/Junior School <span class="red-star">&#9733;</span></label>
		    	<div class="col-sm-4">

		    	{!! Form::text("jschool[name]",null, ["class"=>"form-control",  "placeholder"=>"Name Junior or Upper Basic School Attended"]) !!}

		    	</div>
		    	<label for="inputJuniorYear" class="col-sm-2 control-label">Year Completed <span class="red-star">&#9733;</span></label>
		    	<div class="col-sm-4">
		    	{!! Form::text("jschool[year]",null, ["class"=>"form-control",  "placeholder"=>"Year Completed"]) !!}

		    	</div>
		  	</div>
		  	&nbsp;&nbsp;&nbsp;&nbsp;

@else

@foreach ($data->person['education'] as $index => $contact)

		  	<div class="form-group">
{{-- 		  	 <label for="inputSenior" class="col-sm-2 control-label">{!! ucwords($contact['schType']) !!}<span class="red-star">&#9733;</span></label>
		    	<div class="col-sm-4">

		    	    {!! Form::text("school[type]",$contact['schType'], ["class"=>"form-control",  "placeholder"=>"Name of Senior or High School Attended"]) !!}

		    	</div> --}}
		    	<?php $type = $contact['schType']; ?>
		    	<label for="inputSenior" class="col-sm-2 control-label">{!! ucwords($type) !!}<span class="red-star">&#9733;</span></label>
		    	<div class="col-sm-4">

		    	    {!! Form::text("school[$type][name]",$contact['school'], ["class"=>"form-control",  "placeholder"=>"Name of Senior or High School Attended"]) !!}

		    	</div>
		    	<label for="inputSeniorYear" class="col-sm-2 control-label">Year Completed <span class="red-star">&#9733;</span></label>
		    	<div class="col-sm-4">
		    	{!! Form::text("school[$type][year]",$contact['year'], ["class"=>"form-control",  "placeholder"=>"Year Completed"]) !!}

		    	</div>
		  	</div>
		  	&nbsp;&nbsp;&nbsp;
@endforeach


@endif



		  	<div class="form-group">
		    	<label for="inputSkills" class="col-sm-3 control-label legend">SKILLS OR COMPETENCES <span class="red-star">&#9733;</span></label>
		    </div>
		    <div class="form-group">
			    <div class="col-sm-6">
			    {!! Form::textarea('skills', null,["placeholder"=>"Please specify your skills or competences here"]) !!}
			    </div>
		  	</div>
		  	&nbsp;&nbsp;&nbsp;

			<div class="form-group">
		    	<label for="inputSkills" class="col-sm-5 control-label legend">WHY DO YOU WANT TO BE A MEMBER OF THE BALANCE?
		    	<span class="red-star">&#9733;</span></label>
		    </div>
		    <div class="form-group">
			    <div class="col-sm-6">
			     {!! Form::textarea('remarks',null, ["placeholder"=>"Explain - give at least three(3) reasons", "rows"=>"7"]) !!}
			    	
			    </div>
		  	</div>
		


		  	</div>
		  	&nbsp;&nbsp;&nbsp;

resources/views/__partials/data/unapproved.blade.php
							<table class="table table-hover all-members">
								<thead>
									<tr>
										<th>#</th>
										<th>Full Name</th>
										<th>Gender</th>
										<th>Nationality</th>
										<th>Occupation</th>
										<th>Address</th>
										<th>Phone</th>
										<th>Email</th>
										<th>Date</th>
										<th>Status</th>
									</tr>
								</thead>
								<tbody>
								    @if(!isset($data) and empty($data))
								    <tr>
								        <td colspan="10"><strong>Sorry there are no members yet!</strong></td>
								    </tr>
								    @else
								        @foreach($data as $key => $value)
								        <tr>
								                <td>{{$key + 1}}</td>
								                <td><a href="#">{{ucwords($value['person']['fullname'])}}</a></td>
								                 <td>{{ucwords($value['person']['gender'])}}</td>
								                <td>{{ucwords($value['person']['nationalities'])}}</td>
								                <td>{{ucwords($value['person']['occupation'])}}</td>
								                <td>
								                    @if(isset($value['person']['contacts']))
                                                        {{ucwords($value['person']['contacts']['address'])}}
								                    @else
								                     -
								                    @endif
								                </td>
								                <td>
   								                    @if(isset($value['person']['contacts']))
                                                           {{ucwords($value['person']['contacts']['phone'])}}
   								                    @else
   								                     -
   								                    @endif
   								                </td>
								                <td>
   								                    @if(isset($value['person']['contacts']))
                                                           {{ucwords($value['person']['contacts']['email'])}}
   								                    @else
   								                     -
   								                    @endif
   								                </td>
   								                 <td>{{$value['person']['created_at']}}</td>
   								                 <td>
                                                      @if($value['status'] == 1)
                                                        <a href="{{route('memberships.show',[$value['id'],'setstatus'=>0])}}" class="label label-success">Approved</a>
                                                      @else
                                                       <a href="{{route('memberships.show',[$value['id'],'setstatus'=>1])}}" class="label label-warning">unapprove</a>
                                                      @endif
                                                  </td>
								        </tr>
                                        @endforeach
								    @endif

								</tbody>
							</table>